---
title: "project part 1"
output:
  output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

load("autos.Rdata")

library(tidyverse)
library(lubridate)
```
Problems:

1. posting dates are not random, data retrieved during a small 1-2 month window 


Solvable Problems:

1. in German

1. many NA's coded as 999... or empty string ""

1. registration date is separate

1. postal code is coded as continuous

1. nrOfPictures is all 0's

1. fake values make price drop off at extremes where the price should be higher. e.g. powerPS

1. 


```{r clean}
test$train <- FALSE
train$train <- TRUE

autos <- bind_rows(test, train) %>%
  filter(
    yearOfRegistration < 2022,
    yearOfRegistration > 1900,
    powerPS < 1000,
    price > 0
    ) %>%
  mutate(
    nrOfPictures = NULL,
    name = NULL,
    price = na_if(price, 99999999),
    dateCreated = ymd_hms(dateCreated),
    lastSeen = ymd_hms(lastSeen),
    registered = make_date(yearOfRegistration, monthOfRegistration),
    postalCode = as.character(postalCode),
    weekDayCreated = as.character(wday(dateCreated, label = TRUE)),
    monthOfRegistration = as.character(month(registered, label = TRUE))
    ) %>% 
  mutate_if(is.character, na_if, "")

test.clean <- filter(autos, train == FALSE)
train.clean <- filter(autos, train == TRUE)
save(test.clean, train.clean, file = "autos_clean.Rdata")
```


```{r visualize, message=FALSE, warning=FALSE}
cor(select_if(autos, is.numeric), use = "complete.obs")

options(scipen = 999)
train.clean %>% ggplot() +
  geom_bar(aes(as.factor(month(dateCreated)), fill = as.factor(year(dateCreated))))

train.clean %>% ggplot() +
  geom_bar(aes(as.factor(year(dateCreated))))

train.clean %>%  ggplot() +
  geom_density(aes(price), fill = "blue", alpha = 0.2) +
    scale_x_log10()
              

train.clean %>% 
  pivot_longer(c(kilometer, powerPS), names_to = "variable", values_to = "value") %>% 
  ggplot(aes(value, price)) +
    geom_point() +
    geom_smooth() +
    facet_wrap(vars(variable), scales = "free_x", ncol = 2) +
    ylim(c(0, 100000))

train.clean %>% 
  pivot_longer(c(seller, offerType, abtest, gearbox, fuelType, notRepairedDamage), names_to = "variable", values_to = "value") %>% 
  ggplot(aes(value, price)) +
    geom_bar(stat = "summary", fun.y = "mean") +
    facet_wrap(vars(variable), scales = "free_x", ncol = 3) +
    ylab("Average Price")

train.clean %>% 
  pivot_longer(c(vehicleType, brand), names_to = "variable", values_to = "value") %>% 
  ggplot(aes(value, price)) +
    geom_bar(stat = "summary", fun.y = "mean") +
    facet_wrap(vars(variable), scales = "free", ncol = 1) +
    ylab("Average Price")

train.clean %>%
  pivot_longer(c(monthOfRegistration, weekDayCreated), names_to = "variable", values_to = "value") %>%
  ggplot(aes(value, price)) +
    geom_bar(stat = "summary", fun.y = "mean") +
    facet_wrap(vars(variable), scales = "free_x", ncol = 2) +
    ylab("Average Price")
     ```